### ISSUE TITLE
csv compatibility with flusshygiene plattform

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/flusshygiene-berlin-data-transfer#6]
please check if the csv files generated by the script are compatible with the requirements of the flusshygiene url-import requirements. if csv need another format, columns, etc. please append to this issue, so i can fix this.

**Comment by fabianmoronzirfas** [comment]
The files needed are not CSV it is a JSON.

We need the following structure https://cronbot-sources.now.sh/?count=1 can be used for any value except for EC & IE (Escherichia coli & Intestinale Enterokokken)

```json
{
  "data": [
    {
      "date": "2020-09-07 15:36:24",
      "value": 102
    },
    {
      "date": "2020-09-07 15:36:25",
      "value": 799
    },
    {
      "date": "2020-09-07 15:36:26",
      "value": 901
    }
  ]
}
```

If it is more then one value per day you need to have timestamps that at least are 1 second away from each other. Duplicate values will be filtered.

If you have EC & IE (Escherichia coli & Intestinale Enterokokken)

you have to provide values like this https://cronbot-sources.now.sh/?count=3&type=conc

```json
{
  "data": [
    {
      "date": "2020-09-07 15:36:24",
      "conc_ec": 606,
      "conc_ic": 724
    },
    {
      "date": "2020-09-07 15:36:25",
      "conc_ec": 508,
      "conc_ic": 955
    },
    {
      "date": "2020-09-07 15:36:26",
      "conc_ec": 256,
      "conc_ic": 698
    }
  ]
}
```

**Comment by fabianmoronzirfas** [comment]
We need one distinct url per bathingspot

**Comment by sebastian-meier** [comment]
The script now produces json and csv
