### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/flusshygiene-berlin-data-transfer#7]
I guess the tests are failing because the the AWS keys are not present as ENV variables.

You have two options

1. Add them as SECRETS to the github/travis and import these secrets as env variables to your travis.yml or test.yml (for github actions).
2. (Which I prefer) Mock AWS SDK. Makes it less dependent on the external resources.

I mocked the S3 part of the aws-sdk [here](https://github.com/technologiestiftung/flusshygiene/blob/master/packages/postgres-api/__mocks__/aws-sdk.ts). 
You just have to add a folder called `__mocks__` to your repo and import that mock into your test by adding `jest.mock("aws-sdk")` like done [here](https://github.com/technologiestiftung/flusshygiene/blob/master/packages/postgres-api/__tests__/jest.setup.after-env.ts).

You can do this on jest setup files or directly in your test. See [these docs](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules) as well

**Comment by fabianmoronzirfas** [comment]
🎉 for writing tests!!!1!! Thank you

**Comment by sebastian-meier** [comment]
no time at the moment...
